### ISSUE TITLE
Issues with pip installed package

### ISSUE THREAD

**Issue by shon** [Lanseuo/boardify#1]
So pip installed boardify and I tried the example in README, faced below issues

- package missed
  - charts/ directory
  - index.html
- BarChart params
``
File "dash.py", line 46, in data
    return BarChart(data, label="Fruits").generate()
TypeError: __init__() got an unexpected keyword argument 'label'
``
- JS Error: I locally fixed issues but finally charts failed to render with console error
``
TypeError: "Fruits" is not a non-null object [Chart.min.js:10:62042]
TypeError: l._view is undefined
``

Loved the idea though :)

**Comment by LucasHild** [comment]
Thank you for your feedback. I fixed those both issues and I pushed a new version to PyPi.  
You can install it by typing:

```
pip install --upgrade boardify
```

I updated the example in README.md too. Please have a look. If you still get any errors, feel free to tell me!
