### ISSUE TITLE
Example Chart not rendered

### ISSUE THREAD

**Issue by shon** [Lanseuo/boardify#2]
Hey @Lanseuo ,

Thanks for fixing #1 . I tried boardify again today with example code in README. 
While most part was smooth, bar chart in "Nicest Fruit" block wasn't visible. I am attaching screenshot.
I suspect data passing to chart.js.
![screenshot from 2018-06-20 23-55-56](https://user-images.githubusercontent.com/89816/41677292-8377415c-74e5-11e8-8846-ce9a656100b8.png)

Thanks.

**Comment by LucasHild** [comment]
Hello,

I'm sorry for the inconvenience. Could you please upgrade to the latest version and use the new example in README.md.

If the chart is still not visible, please open the developer tools of your browser (F12) and go to the tab "Console". Are there any errors?

Please also send me the generated HTML. You can find it here: [view-source:http://localhost:7000/](view-source:http://localhost:7000/).

**Comment by LucasHild** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue with the latest version.

Thank you!
